### ISSUE TITLE
tags_explaination: typo

### ISSUE THREAD

**Issue by melicarls** [sf-wdi-27-28/publify_debugging_lab_28#42]
This app uses 18 instances of the variable '.tags_explaination' when it should be spelled '.tags_explanation'

**Comment by nathanallen** [comment]
Great! Let's move this issue upstream to https://github.com/publify/publify

Then, please cross-reference it here and close this issue.

**Comment by melicarls** [comment]
Done! 
https://github.com/publify/publify/issues/698
